# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

#
# General Settings
#
box: bento/centos-6.7
chef_cookbook_path: ./provision

#
# Virtual Machine Settings
#
memory: 1024
cpus: 1

#
# Network Settings
#
hostname: undotsushin.local
ip: 192.168.33.50
sync_folder: 'public' # sync :

#
# Apache
#
document_root: '/vagrant/public'

#
# User and Group
#
user: vagrant
group: vagrant


#
# Linked Clone for Vagrant v1.8
#
linked_clone: false


#
# ssh settings for $ vagrant push - default
# ==============================
#
# profile.ymlで設定する値のデフォルト値
# 詳細は _profile.yml参照
#
ssh_user : username
ssh_host : undotsushin.com

