<?php

$SITE="運動通信";
$KEYWORD="運動通信";
$DESCRIPTION="運動通信";
$MAILFROM="psychsa@gmail.com";
$MAILTO="psychsa@gmail.com";
$TAGON=1;
$SORC=0;
$PAGEOFFSET=10;
$MAXFILESIZE=2;
$ALTDEFAULT="#";
$EDITCONFIGURATION_h1img=402;
$EDITCONFIGURATION_alimg=402;
$EDITCONFIGURATION_lrimg=200;

?>