<?php

$SITE="運動通信";
$KEYWORD="運動通信";
$DESCRIPTION="運動通信";
$MAILFROM="psychsa@gmail.com";
$MAILTO="psychsa@gmail.com";
$TAGON=1;
$SORC=0;
$ADMINUSR=1;
$PAGEOFFSET=100;
$IMGRESIZE=1;
$MAXFILESIZE=20;
$ALTDEFAULT="#";
$EDITCONFIGURATION_h1img=530;
$EDITCONFIGURATION_alimg=530;
$EDITCONFIGURATION_lrimg=250;
$TRACKBACK=0;

?>